learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path('other/',views.other,name='other'),
    path('relative/',views.relative,name='relative'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    re_path(r'^basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url.html')
    

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <ul class="navbar-nav">
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'index' %}">BRAND</a>
          </li>
          </ul>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>

          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:relative' %}">RELATIVE</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:other' %}">OTHER</a>
          </li>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
        <!-- Anything here is not inherited -->
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Welcome to INDEX</h1>
    <h2>We are in Index.html</h2>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Welcome to OTHER</h1>
    <h2>This is an example of the template Inheritance</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>Welcome to Relative_urls</h1>
    <h2>Now you are in relatives.html file</h2>
{% endblock %}